### ISSUE TITLE
Entities are invisible when certain configs are opened.

### ISSUE THREAD

**Issue by RandomGuy91** [MrCrayfish/Catalogue#44]
I am having thisa issue, and so did a lot of other people. Here is a link to the reddit thread so you can see whats going on, bc I honestly don't. https://www.reddit.com/r/feedthebeast/comments/w79efx/all_entities_are_invisible_upon_loading_the_world/
Just thought new users shouldn't have to figured this out.

**Comment by IdrisQe** [comment]
Oh, hey, thanks for linking that. I thought I had reported this issue after discovering it and posting about it in the comments of that post but it appears I forgot to. (ADHD sucks)

If I recall right, the issue is caused because some mods use 3d entity models as their creative menu icon, and the creative menu icon gets picked up by Catalogue and used as the mod's icon on the menu if none is provided by the mod, but Catalogue expects mods to use Blocks or Items, not Entities, and the way some mods load models is that the entity models are only loaded upon entering a world, so if you open Catalogue before entering a world, it tries to load the models, fails since a world is not open, and soft-crashes the renderer kind of, making it so when you DO enter a world, anything using that renderer (entities, particles, etc.) will fail to render.

That's just my vague recollection of someone else's explanation admittedly. I think it may have been the Alex's Mobs dev who figured that out, since that's the mod many people had issues with originally, and I may have reported it there at first thinking it was an issue on their end only since it was the only mod causing it for me.

**Comment by MrCrayfish** [comment]
It's caused by Alex Mobs. The mod has been patched on 1.18.2 and 1.19+, however the 1.18.2 version with the patch has not been released. I've gone ahead and opened an issue on their repo https://github.com/AlexModGuy/AlexsMobs/issues/1547

**Comment by RandomGuy91** [comment]
Ok, thx for letting me know. :)
